---
name: grept
on:
  schedule:
    - cron: '43 0 * * 0'
  workflow_dispatch:
    inputs:
      query:
        description: '(Optional) GitHub search query for repos in the Azure organization'
        type: string
        required: false
        default: null

permissions:
  issues: write

jobs:
  getrepos:
    name: get repos
    runs-on: ubuntu-latest
    env:
      query: "terraform-azurerm-avm-res-keyvault"
    outputs:
      repoarray: ${{ steps.graphql.outputs.repoarray }}
    steps:
      - name: query GitHub graphql API
        id: graphql # TODO replace with CSV output when ready
        run: |
          RESULT=$(gh api graphql --paginate -f query='query {
            search(query: "${{ inputs.query || env.query }} user:azure", type: REPOSITORY, first: 100) {
                repositoryCount
                edges {
                  node {
                    ... on Repository {
                      name
                    }
                  }
                }
              }
            }')
          NUMREPOS=$(echo $RESULT | jq '.data.search.repositoryCount')
          echo "Number of repos found: $NUMREPOS"
          REPOARRAY=$(echo $RESULT | jq -c '.data.search.edges | [.[].node.name]')
          echo repoarray="$REPOARRAY"
          echo repoarray="$REPOARRAY" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  governance:
    name: governance
    runs-on: ubuntu-latest
    needs: getrepos
    env:
      GITHUB_USER: matt-FFFFFF
      GREPT_CONFIG: "git::https://github.com/Azure/Azure-Verified-Modules-Grept.git//terraform"
    outputs:
      result: ${{ steps.set-output.outputs.result }}
    strategy:
      max-parallel: 5
      matrix:
        repo: ${{ fromJson(needs.getrepos.outputs.repoarray) }}
        exclude:
          - repo: "terraform-azurerm-avm-template"
      fail-fast: false
    steps:
      - name: set env result=success
        run: |
          echo 'result=success' >> "$GITHUB_ENV"

      - name: install go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe #v4.1.0
        with:
          go-version: '1.21'

      - name: install grept
        run: |
          go install github.com/Azure/grept@latest

      - name: checkout remote
        id: checkout
        run: |
          git clone "https://${{ env.GITHUB_USER }}:${{ secrets.USER_PAT }}@github.com/Azure/${{ matrix.repo }}.git"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: grept apply and auto remediate
        run: |
          grept apply --auto ${{ env.GREPT_CONFIG }}
        working-directory: ${{ matrix.repo }}
        env:
          OVERRIDE_GITHUB_REPOSITORY: Azure/${{ matrix.repo }}
          OVERRIDE_GITHUB_REPOSITORY_OWNER: Azure
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: detect changes
        id: changes
        run: |
          if [[ -z $(git status -s) ]]; then
            echo "No changes detected"
            echo 'detected=false' >> "$GITHUB_OUTPUT"
            exit 0
          fi
          echo "Changes detected"
          echo 'detected=true' >> "$GITHUB_OUTPUT"
        working-directory: ${{ matrix.repo }}

      - name: commit changes to branch and push to origin
        if: steps.changes.outputs.detected == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          BRANCH="grept-apply-$(date +%s)"
          git checkout -b "$BRANCH"
          git add .
          git commit -m "fix: grept apply"
          git push --set-upstream origin "$BRANCH"
        working-directory: ${{ matrix.repo }}

      - name: create pull request
        if: steps.changes.outputs.detected == 'true'
        id: pr
        run: |
          PR_URL=$(gh pr create --title "fix: repository governance" --body "This PR was automatically created by the AVM grept governance tool")
          echo pull-request-number=$(gh pr view $PR_URL --json number | jq -r '.number') >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.USER_PAT }}
        working-directory: ${{ matrix.repo }}

      - name: close and comment out of date prs
        if: steps.changes.outputs.detected == 'true'
        run: |
          PULL_REQUESTS=$(gh pr list --search "fix: repository governance" --json number)
          echo "$PULL_REQUESTS" | jq -r '.[] | select(.number != ${{ steps.pr.outputs.pull-request-number }}) | .number' | xargs -I {} gh pr close {} --delete-branch --comment "Supersceeded by #${{ steps.pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.USER_PAT }}
        working-directory: ${{ matrix.repo }}

      - name: set env result=failure
        if: ${{ failure() }}
        run: |
          echo 'result=failed' >> "$GITHUB_ENV"

      - name: set output
        if: ${{ always() }}
        id: set-output
        run: |
          echo "result=${{ env.result }}" >> "$GITHUB_OUTPUT"

  report:
    name: report
    runs-on: ubuntu-latest
    needs: governance
    if: ${{ failure() }}
    steps:
      - name: raise issue
        run: |
          ## BLOCKED on matrix outputs: https://github.com/actions/runner/pull/2477
          ## gh issue create --repo ${{ github.repository }} --title "Repository governance failure" --body "The following repositories failed governance checks:\n\n```json\n${{ toJSON(join(needs.governance.outputs)) }}\n```\n"
          gh issue create --repo ${{ github.repository }} --title "Repository governance failure" --body "The following repositories failed governance checks: <${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id}}>"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
